name: Deploy Java Web App (WAR) to EC2

on:
  push:
    branches:
      - master  # Trigger on changes to master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR file
        run: |
          mkdir -p target
          javac -d target $(find src -name "*.java")
          cp -r src/main/webapp target/ROOT

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/ROOT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: war-file
          path: ROOT

      - name: Deploy to AWS EC2 (Tomcat)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo systemctl stop tomcat9
            sudo rm -rf ${{ secrets.DEPLOY_PATH }}/ROOT
            sudo mv ~/ROOT ${{ secrets.DEPLOY_PATH }}/ROOT
            sudo systemctl start tomcat9
