name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - master  # Change if your branch is "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        
      - name: Set OpenSSL Legacy Provider  # 🔹 Add this step
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV

      - name: Build React App
        run: CI=false npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build/

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/react-app
            sudo rm -rf /var/www/react-app/*
            sudo mv ~/build/* /var/www/react-app/
            sudo chown -R www-data:www-data /var/www/react-app
            sudo systemctl restart nginx
